[gcp_service_account]
type = "service_account"
project_id = "aixr-401704"
private_key_id = "9c3e00ec5dc52d39e1df88b6e74e45faad4b1d84"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCy9yYryUysnxD9
0x6QduIfy1J6VGXXp4HXp/JP5x8yK+RFcsFHklp4QlRNIlsprYo5GX/H9wuhOBu4
7hjsYgmCv4O+4rSUSwFDTIvq1Ms1j/Ybdw4T+5iRXUNt5ys0LgE3Kt08UdkhSKuU
EHPpb5Z4Ad31IlxGJT/P9vjCAHO3vocs6q0WwgyIrPwHgCGkZIBUqZ7Aj4CYHUs3
mjKtRXfIj7OFO6Ev+l17xTJ8dWvlU6bPO4QImzKbaRIiIUhb2C9eZNeBf914da5f
ji4EhRosZdYUoadEaPJvkwvs+gPu2ZIH7MsqyZphaEoulrTi98gVv/gnA+p0DqOV
+5rcrOB9AgMBAAECggEABtX0XgtKE7TesgdInVWBJRw/yf7jxfU2uy1FzuIB2cl9
5l4v/kMblAjajfiwOTsQ8sXj0NhBmDabrnhfuNW0zcrxZg7kPV7RDUhE9uMKYQEe
8iUdw0sipHjGvNGt34gbUUdgnG925vPO4/Ct8L5rpalSmEyn8CD3m0KwdT6NrPi4
ZMHLvYuTwUd7dJJLEn9nIgsYE5hCOTbcrVnm1Y0sQKc2ZGvWLHv39rVzOLrqExdt
BxkL9IY0jTKilpysNo0zW9qN+qay7IPX9bdMrR1mpQogBBsjVpAITU7t/0pxbOI8
et6qYfy+DOnnHKq6VrjgrarG71VM1J4yC5mI6/DZUQKBgQDr6NOuw2LnNvlqTak/
Y00ehMSWvdtZZCG1UvgtE/nOg3PLpB1VN7FHEFODUdOCgKYm4+v4s3QACgMi0AWF
wUOS6sI2Wq9LpHobu5ZNJPPlgw2aOvTdtFfOePVSSz2et1q15lnW66h+5tyQMjDW
wpqV/Mb4NHntjLpSvH5bX3p3DQKBgQDCNNu0U34aHCp7WXp4iBE1Bk2WS70/d/tK
MZSuwNi7q5WMPAKmPSXWGeUZiAodwN8WRl82FfYTdo8/PiPBQF0+IV7K2wRCCbJa
KE0G2UUXrMTCTs5cuueOpOgX2Su3bn+qmPS4m/maUzQOMhrAf+kU5U6JJygtpGsh
V4ZzKXazMQKBgDMZt+C/Sgkzi0tPjz2/0NCvibXtYjo2ymZwlnmNPitRph+SaRgw
fCIckzp62woFu/fonxC8LoBjqtI7pTaX6n9EgtUrR5VnB1xCgggr3Pj2LlgeNTRh
ADQlV16AFdTveqK0RvmbCmCSuWwyswmSFdIvcxoIo/Ck7ydE1UoNoIVxAoGBAKZX
rA+qrAolMeXxYEs5ELQAMBiZywE//YcxLI76Mymb8D3rcMF/Apd+GpNhyHhvqSVl
JUwoR1uoY03iJbHzNWpwHsdWDTGbKJ68gi1pkBqVKvrbkTowBQJTEVDL/Pvis4sl
9Abj4kljFuVJ2UwkwznYpwom9e0SNYibdVfSng8hAoGAFliw036tDCBhpaTYlxOW
ZD5OGs90ec0PhVYlH9W9QiRZFc+JJEBG6KUlxMYXQjP78GDF9nOZ5fcB7P7cJf4T
hd8jVk55AIOpH06ZajbJyGQmOBxwac3dofsTj/aXWejAGVObm8ZhouHjSnHsgSWE
oCshUPiACJFpWgNkvvhv0Qk=
-----END PRIVATE KEY-----
"""
client_email = "aixr-401704@appspot.gserviceaccount.com"
client_id = "107413214425515391033"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/aixr-401704%40appspot.gserviceaccount.com"
universe_domain = "googleapis.com"